import { SEO } from '../components/SEO'
import { Button } from '../components/ui/button'
import { Card } from '../components/ui/card'
import { Input, Textarea } from '../components/ui/input'

const audiences = ['Industrial Associations / Corporates', 'Educational Institute — Colleges', 'Educational Institute — Schools', 'India Inbound']
const industries = ['Automotive', 'Manufacturing', 'Aerospace', 'Renewable Energy', 'Semiconductors', 'Pharmaceuticals', 'Biotech', 'Agriculture', 'Dairy', 'Food & Beverage', 'Textiles', 'Hospitality', 'Logistics', 'IT & Software', 'Artificial Intelligence', 'FinTech', 'Education', 'Media', 'Architecture', 'Tourism', 'Sustainability']
const destinations = ['Europe', 'USA', 'United Kingdom', 'Germany', 'Japan', 'China', 'Singapore', 'UAE', 'Australia', 'India', 'Vietnam', 'Germany & Denmark']

export function KnowledgeToursPage() { return <main><SEO title="Knowledge Tours | Tibro" description="Curated global industry and academic learning experiences." path="/knowledge-tours" /><section className="mx-auto max-w-7xl px-5 py-20"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Educational Travel 101</p><h1 className="mt-4 font-serif text-7xl leading-none">Industrial Visits & Knowledge Tours.</h1><p className="mt-5 max-w-3xl text-xl text-stone-600">The world is the best classroom. We build programmes around factory visits, industry interactions, trade-fair participation, university collaborations and expert-led sessions.</p><Button className="mt-8">Talk to a specialist</Button></section><Shelf title="Explore Tours by your profile" items={audiences} /><Shelf title="Explore Tours by Industry" items={industries} /><Shelf title="Explore Tours by Destination" items={destinations} /><section className="mx-auto max-w-7xl px-5 py-16"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">In the spotlight</p><h2 className="mt-4 font-serif text-5xl">Three programmes we run every year.</h2><Card className="mt-8"><p className="font-mono text-xs uppercase tracking-[0.25em] text-stone-500">Dairy · Australia</p><h3 className="mt-3 text-3xl font-semibold">A Dairy Knowledge Tour to Australia</h3><p className="mt-3 text-stone-600">Exploring the Australian dairy value chain from pristine pastures to advanced processing facilities.</p><p className="mt-5 font-semibold">9 nights / 10 days · 5 cities</p></Card></section><section className="mx-auto max-w-4xl px-5 py-16"><Card><h2 className="font-serif text-5xl">Tell us who's travelling.</h2><form className="mt-8 grid gap-4"><Input placeholder="No. of Travellers" /><Input placeholder="Audience type" /><Input placeholder="Tour interest" /><Textarea placeholder="What should they come home knowing?" /><Button>Request a call</Button></form></Card></section></main> }
function Shelf({ title, items }: { title: string; items: string[] }) { return <section className="mx-auto max-w-7xl px-5 py-12"><h2 className="font-serif text-5xl">{title}</h2><div className="mt-8 grid gap-4 md:grid-cols-3 lg:grid-cols-4">{items.map((item) => <Card key={item}><h3 className="text-xl font-semibold">{item}</h3><p className="mt-3 text-sm text-stone-600">Curated access, expert sessions and logistics designed around this brief.</p></Card>)}</div></section> }
