import { Link, useParams } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'
import { SEO } from '../components/SEO'
import { Button } from '../components/ui/button'
import { Card } from '../components/ui/card'
import { Input, Textarea } from '../components/ui/input'
import { allTours, collections, countryHubs, getTour, regions, slugify } from '../data/site'

function TourCard({ tour }: { tour: (typeof allTours)[number] }) {
  return <Link to={`/luxury-holidays/${tour.id}`}><Card className="h-full transition hover:-translate-y-1 hover:shadow-xl"><p className="font-mono text-xs uppercase tracking-[0.25em] text-stone-500">{tour.country}</p><h3 className="mt-3 text-2xl font-semibold">{tour.title}</h3><p className="mt-3 text-stone-600">{tour.tagline}</p><p className="mt-5 text-sm font-bold">{tour.durationLabel} · {tour.priceFromDisplay}</p></Card></Link>
}

export function LuxuryHome() {
  return <main><SEO title="Luxury Holidays — Tibro" description="Browse luxury domestic and international journeys curated by Tibro travel designers." path="/luxury-holidays" />
    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.85fr_1.15fr]"><div><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">391 journeys · 60 countries · since 1991</p><h1 className="mt-4 font-serif text-7xl leading-none md:text-8xl">Luxury<br />Holidays</h1><div className="mt-8 flex gap-3"><Button asChild><a href="#catalog">Find your journey</a></Button><Button asChild variant="outline"><Link to="/luxury-holidays/all">Browse catalog</Link></Button></div></div><Card className="bg-stone-950 text-amber-50"><p className="font-mono text-xs uppercase tracking-[0.3em] text-amber-200">Browse the atlas</p><div className="mt-6 flex flex-wrap gap-3">{regions.map((region) => <Link key={region} to={`/luxury-holidays/regions/${slugify(region)}`} className="rounded-full border border-amber-100/30 px-4 py-2 hover:bg-amber-50 hover:text-stone-950">{region}</Link>)}</div></Card></section>
    <section className="mx-auto max-w-7xl px-5 py-12"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Browse by country</p><h2 className="mt-4 font-serif text-5xl">The most-asked-for countries.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{countryHubs.map((hub) => <Link key={hub.country} to={`/luxury-holidays/countries/${slugify(hub.country)}`}><Card><p className="text-sm text-stone-500">{hub.journeys} journeys</p><h3 className="mt-3 text-3xl font-serif">{hub.country}</h3><p className="mt-3 text-stone-600">{hub.copy}</p></Card></Link>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-12"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Curated journeys</p><h2 className="mt-4 font-serif text-5xl">Twelve ways to begin a journey.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{collections.map(([name, copy]) => <Link key={name} to={`/luxury-holidays/collections/${slugify(name)}`}><Card className="h-full"><h3 className="text-2xl font-semibold">{name}</h3><p className="mt-3 text-stone-600">{copy}</p><p className="mt-5 text-sm font-bold">Open collection</p></Card></Link>)}</div></section>
    <section id="catalog" className="mx-auto max-w-7xl px-5 py-16"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Trending</p><h2 className="mt-4 font-serif text-5xl">Open the page.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{allTours.map((tour) => <TourCard key={tour.id} tour={tour} />)}</div></section><EnquiryBlock /></main>
}

export function LuxuryListing() { return <FilteredListing title="Browse the full catalogue" tours={allTours} path="/luxury-holidays/all" /> }
export function RegionPage() { const { region = '' } = useParams(); const tours = allTours.filter((t) => slugify(t.region) === region); return <FilteredListing title={`${region.replace(/-/g, ' ')} journeys`} tours={tours.length ? tours : allTours} path={`/luxury-holidays/regions/${region}`} /> }
export function CountryPage() { const { country = '' } = useParams(); const tours = allTours.filter((t) => t.countries.some((c) => slugify(c) === country) || slugify(t.country) === country); return <FilteredListing title={`${country.replace(/-/g, ' ')} holidays`} tours={tours.length ? tours : allTours} path={`/luxury-holidays/countries/${country}`} /> }
export function CollectionPage() { const { collection = '' } = useParams(); const label = collection.replace(/-/g, ' '); const tours = allTours.filter((t) => t.themes.some((theme) => slugify(theme) === collection)); return <FilteredListing title={`${label} collection`} tours={tours.length ? tours : allTours} path={`/luxury-holidays/collections/${collection}`} /> }

function FilteredListing({ title, tours, path }: { title: string; tours: typeof allTours; path: string }) { return <main><SEO title={`${title} — Tibro`} description="Hand-edited Tibro luxury holiday shelf." path={path} /><section className="mx-auto max-w-7xl px-5 py-20"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Luxury Holidays</p><h1 className="mt-4 capitalize font-serif text-6xl">{title}</h1><div className="mt-10 grid gap-5 md:grid-cols-3">{tours.map((tour) => <TourCard key={tour.id} tour={tour} />)}</div></section></main> }

export function TourPage() { const { id = '' } = useParams(); const tour = getTour(id); if (!tour) return <FilteredListing title="Journey not found" tours={allTours} path={`/luxury-holidays/${id}`} />; return <main><SEO title={`${tour.title} | Tibro`} description={tour.tagline} path={`/luxury-holidays/${tour.id}`} />
  <section className="bg-stone-950 text-amber-50"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1fr_.8fr]"><div><p className="font-mono text-xs uppercase tracking-[0.35em] text-amber-200">A Tibro Journey</p><h1 className="mt-4 font-serif text-7xl leading-none">{tour.title}</h1><p className="mt-6 text-xl text-stone-300">{tour.tagline}</p><div className="mt-8 flex flex-wrap gap-3 text-sm"><span>{tour.duration}</span><span>·</span><span>{tour.country}</span><span>·</span><span>From {tour.priceFromDisplay}</span></div></div><Card className="bg-amber-50 text-stone-950"><p className="font-mono text-xs uppercase tracking-[0.3em] text-stone-500">Best for</p><p className="mt-4 text-2xl font-semibold">{tour.themes.join(' · ')}</p><Button asChild className="mt-8 w-full"><a href="#enquire">Talk to a Tibro designer</a></Button></Card></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Signature moments</p><h2 className="mt-4 font-serif text-5xl">Three mornings you'll remember.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{tour.highlights.map((h, i) => <Card key={h}><p className="font-mono text-sm text-stone-500">No. {String(i + 1).padStart(2, '0')}</p><h3 className="mt-4 text-2xl font-semibold">{h}</h3></Card>)}</div></section>
  <section className="bg-white/60 py-16"><div className="mx-auto max-w-7xl px-5"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">The Route</p><h2 className="mt-4 font-serif text-5xl">Your {tour.country}, mapped.</h2><div className="mt-8 flex flex-wrap gap-3">{tour.route.map((stop, i) => <span key={stop} className="rounded-full bg-stone-950 px-4 py-2 text-sm text-amber-50">{i + 1}. {stop}</span>)}</div></div></section>
  <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[.35fr_.65fr]"><div><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Day by day</p><h2 className="mt-4 font-serif text-5xl">{tour.duration}, in order.</h2></div><div className="grid gap-5">{tour.itinerary.map((day, i) => <Card key={day.title}><p className="font-mono text-sm text-stone-500">Day {i + 1}</p><h3 className="mt-2 text-2xl font-semibold">{day.title}</h3><p className="mt-3 text-stone-600">{day.body}</p></Card>)}</div></section>
  <section className="mx-auto grid max-w-7xl gap-5 px-5 py-16 md:grid-cols-3"><Card><h2 className="font-serif text-4xl">Where you'll stay</h2>{tour.hotels.map((h) => <p key={h.city} className="mt-4"><b>{h.city}</b><br />{h.name}</p>)}</Card><Card><h2 className="font-serif text-4xl">Included</h2><ul className="mt-4 list-disc pl-5 text-stone-600">{tour.inclusions.map((x) => <li key={x}>{x}</li>)}</ul></Card><Card><h2 className="font-serif text-4xl">Honestly</h2><ul className="mt-4 list-disc pl-5 text-stone-600">{tour.fieldNotes.map((x) => <li key={x}>{x}</li>)}</ul></Card></section><EnquiryBlock defaultMessage={`I'm interested in ${tour.title}. Please share details.`} /></main> }

function EnquiryBlock({ defaultMessage = '' }: { defaultMessage?: string }) { return <section id="enquire" className="mx-auto max-w-4xl px-5 py-20"><Card><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Enquire</p><h2 className="mt-4 font-serif text-5xl">Start the conversation.</h2><form className="mt-8 grid gap-4"><Input placeholder="Full name" /><Input placeholder="Email" type="email" /><Input placeholder="Phone" /><Textarea defaultValue={defaultMessage} placeholder="What are you planning?" /><Button>Send Enquiry</Button></form></Card></section> }
