import { SEO } from '../components/SEO'
import { Button } from '../components/ui/button'
import { Card } from '../components/ui/card'
import { Input, Textarea } from '../components/ui/input'
import { offices } from '../data/site'

export function AboutPage() { return <main><SEO title="About Tibro" description="Three decades of moving people meaningfully." path="/about-us" /><section className="mx-auto max-w-7xl px-5 py-20"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">About Tibro</p><h1 className="mt-4 max-w-5xl font-serif text-7xl leading-none">Three decades of moving people, meaningfully.</h1><p className="mt-6 max-w-3xl text-xl text-stone-600">What began as Orbit is now Tibro — a quietly expert house for trade fairs, luxury holidays, corporate tours and knowledge journeys.</p><div className="mt-10 grid gap-4 md:grid-cols-4">{[['30+', 'Years'], ['500+', 'Delegations'], ['60+', 'Countries'], ['8', 'Offices']].map(([v,l]) => <Card key={l}><p className="font-serif text-5xl">{v}</p><p>{l}</p></Card>)}</div></section><section className="bg-white/60 py-16"><div className="mx-auto max-w-7xl px-5"><h2 className="font-serif text-5xl">Built on four quiet promises.</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{['Security & Trust','Flexibility & Customization','Value for Money','Experiential Add-Ons'].map((p) => <Card key={p}><h3 className="text-xl font-semibold">{p}</h3><p className="mt-2 text-stone-600">The quiet confidence of working with a 30-year-old house.</p></Card>)}</div></div></section></main> }

export function ContactPage() { return <main><SEO title="Contact Tibro" description="Reach Tibro offices across India." path="/contact" /><section className="mx-auto max-w-7xl px-5 py-20"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">Contact</p><h1 className="mt-4 font-serif text-7xl">Start a conversation with the team.</h1><div className="mt-10 grid gap-5 lg:grid-cols-[.7fr_.3fr]"><Card><form className="grid gap-4"><Input placeholder="Full name" /><Input placeholder="Email" /><Input placeholder="Phone" /><Textarea placeholder="What are you planning?" /><Button>Send enquiry</Button></form></Card><div className="grid gap-4">{offices.map((office) => <Card key={office.id}><h3 className="text-2xl font-semibold">{office.city}{office.isHeadOffice ? ' · Head Office' : ''}</h3><p className="mt-2 text-sm text-stone-600">{office.addressLines.join(', ')}</p><p className="mt-2 text-sm">{office.phones.join(' · ')}</p></Card>)}</div></div></section></main> }

export function VisaPage() { return <SimplePage path="/visa" eyebrow="Visa services · every country" title="Any border, handled." copy="Wherever in the world you're headed, our visa desk takes care of paperwork, appointments, embassy follow-through and document checks." /> }
export function BlogPage() { return <main><SEO title="Dispatches from the orbit. — The Tibro Journal" description="Field notes from the road." path="/blog" /><section className="mx-auto max-w-7xl px-5 py-20"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">The Journal - Spring 2026</p><h1 className="mt-4 font-serif text-7xl">Dispatches from the orbit.</h1><div className="mt-10 grid gap-5 md:grid-cols-3">{['Royal India, on Rails','Safari at First Light','Bali, Beyond the Beach','The Art of the Corporate Retreat','Inside CES, Honestly','Venetian Nights','A Quiet Morning in Hoi An'].map((story) => <Card key={story}><p className="font-mono text-xs uppercase tracking-[0.25em] text-stone-500">Story</p><h3 className="mt-3 text-2xl font-semibold">{story}</h3><p className="mt-3 text-stone-600">Short stories, quiet photographs, and the small things we learn on the way back.</p></Card>)}</div></section></main> }
export function CareersPage() { return <SimplePage path="/careers" eyebrow="Careers" title="Open positions at Tibro" copy="Tibro hires across sales, marketing and operations. Explore current roles, or send a general application to careers@tibro.in." /> }
export function NotFoundPage() { return <SimplePage path="/404" eyebrow="Not found" title="This journey is still being planned." copy="Use the navigation to return to a live Tibro page." /> }
function SimplePage({ path, eyebrow, title, copy }: { path: string; eyebrow: string; title: string; copy: string }) { return <main><SEO title={`${title} | Tibro`} description={copy} path={path} /><section className="mx-auto max-w-5xl px-5 py-24"><p className="font-mono text-xs uppercase tracking-[0.35em] text-stone-500">{eyebrow}</p><h1 className="mt-4 font-serif text-7xl leading-none">{title}</h1><p className="mt-6 text-xl text-stone-600">{copy}</p><Button className="mt-8">Speak with an advisor</Button></section></main> }
