import { Link, useParams } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { SEO } from '../components/SEO'
import { Button } from '../components/ui/button'
import { Card } from '../components/ui/card'
import { Input, Textarea } from '../components/ui/input'
import { tradeFairPackages } from '../data/tradeFairs'

export function TradeFairsPage() {
  return <main className="tf-plex"><SEO title="Tibro — Curated Trade Fairs, Luxury & Knowledge Tours" description="Global exhibitions sourced and staged with operational precision." path="/trade-fairs" /><section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20"><p className="font-mono text-xs uppercase tracking-[0.35em] text-cyan-200">Business Travel</p><h1 className="mt-4 text-7xl font-semibold tracking-tight">Trade Fairs.</h1><p className="mt-5 max-w-2xl text-slate-300">Global exhibitions, sourced and staged with operational precision.</p><Input className="mt-8 max-w-md border-slate-700 bg-slate-900 text-white" placeholder="Search" /><div className="mt-10 grid gap-4 md:grid-cols-4">{[['100k+', 'Delegates Sent'], ['200+', 'Exhibitions Curated'], ['40+', 'Countries Reached'], ['30+', 'Years In Trade']].map(([v,l]) => <Card key={l} className="border-slate-700 bg-slate-900 text-white"><p className="text-3xl font-semibold">{v}</p><p className="text-slate-400">{l}</p></Card>)}</div></div></section><section className="mx-auto max-w-7xl px-5 py-16"><h2 className="text-3xl font-semibold">Featured trade fair packages</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{tradeFairPackages.map((pkg) => <Link key={pkg.id} to={`/package/${pkg.id}`}><Card className="border-slate-200"><p className="font-mono text-xs uppercase tracking-[0.25em] text-slate-500">{pkg.city}, {pkg.country}</p><h3 className="mt-3 text-3xl font-semibold">{pkg.fairName}</h3><p className="mt-3 text-slate-600">{pkg.summary}</p><p className="mt-5 font-semibold">Pricing from {pkg.pricingFrom}</p></Card></Link>)}</div></section></main>
}

export function PackagePage() {
  const { id = '' } = useParams()
  const pkg = tradeFairPackages.find((item) => item.id === id) || tradeFairPackages[0]
  return <main className="tf-plex"><SEO title={`${pkg.title} | Tibro`} description={pkg.summary} path={`/package/${pkg.id}`} /><section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-16"><Link to="/trade-fairs" className="inline-flex items-center gap-2 text-sm text-cyan-200"><ArrowLeft size={16} /> Back to Trade Fairs</Link><p className="mt-10 font-mono text-xs uppercase tracking-[0.35em] text-cyan-200">Trade Fairs</p><h1 className="mt-4 text-6xl font-semibold tracking-tight">{pkg.fairName}</h1><p className="mt-4 text-xl text-slate-300">{pkg.city}, {pkg.country} · {pkg.duration} · {pkg.date}</p><div className="mt-8 flex gap-3"><Button variant="gold">Enquire Now</Button><span className="rounded-full bg-white px-5 py-3 font-semibold text-slate-950">From {pkg.pricingFrom}</span></div></div></section><section className="mx-auto grid max-w-7xl gap-8 px-5 py-16 lg:grid-cols-[.7fr_.3fr]"><div><h2 className="text-3xl font-semibold">Overview</h2><p className="mt-4 text-slate-700">{pkg.summary}</p><h3 className="mt-10 text-2xl font-semibold">Why Attend</h3><ul className="mt-4 grid gap-3">{pkg.whyAttend.map((item) => <li key={item} className="rounded-2xl bg-white p-4">{item}</li>)}</ul><h3 className="mt-10 text-2xl font-semibold">Itinerary</h3><div className="mt-4 grid gap-4">{pkg.itinerary.map((day, i) => <Card key={day.title}><p className="font-mono text-sm text-slate-500">Day {i + 1}</p><h4 className="text-xl font-semibold">{day.title}</h4><p className="mt-2 text-slate-600">{day.body}</p></Card>)}</div></div><aside className="grid content-start gap-4">{pkg.facts.map((fact) => <Card key={fact.label}><p className="text-3xl font-semibold">{fact.value}</p><p className="text-slate-500">{fact.label}</p></Card>)}</aside></section><section className="mx-auto max-w-5xl px-5 pb-20"><Card><h2 className="text-3xl font-semibold">Register interest</h2><form className="mt-6 grid gap-4"><Input placeholder="Name" /><Input placeholder="Work email" /><Input placeholder="Company" /><Textarea defaultValue={`I'm interested in ${pkg.fairName}. Please share package details.`} /><Button>Send enquiry</Button></form></Card></section></main>
}
